Add PHP 8.2 RC container
Signed-off-by: Julius Härtl <jus@bitgrid.net>

diff --git a/docker/Dockerfile.php73 b/docker/Dockerfile.php73
--- a/docker/Dockerfile.php73
+++ b/docker/Dockerfile.php73
@@ -80,8 +80,9 @@ ADD configs/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
 RUN wget -q -O - https://packages.blackfire.io/gpg.key | sudo apt-key add - \
     && echo "deb http://packages.blackfire.io/debian any main" | sudo tee /etc/apt/sources.list.d/blackfire.list \
     && apt-get update  \
-    && apt-get install -y --no-install-recommends blackfire-php blackfire \
-    && printf "blackfire.agent_socket=tcp://blackfire:8307\n" >> $PHP_INI_DIR/conf.d/zz-blackfire.ini.disabled \
+    && (apt-get install -y --no-install-recommends blackfire-php blackfire \
+		&& printf "blackfire.agent_socket=tcp://blackfire:8307\n" >> $PHP_INI_DIR/conf.d/zz-blackfire.ini.disabled) \
+		|| echo "Skipped blackfire as the installation failed" \
     && rm -rf /var/lib/apt/lists/*
 
 RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
